### ISSUE TITLE
I have questions about customization of gtk3 and gnome-shell theme in general

### ISSUE THREAD

**Issue by Tuxman2** [etiennegnome/EQUILIBRIUM#3]
Hi etiennegnome,

as you are the creator of Linuxmos and Equilibrium themes, and you know how to create gnome themes, I have some questions for you.

First, where are defined the items for the dialog box of GDM login screen in the .css file (gnome-shell) ? The dialog box (with 'cancel' and 'shutdown/restart' buttons) who appears when we want to shutdown or restart the system in the GDM login screen. I will be interested of changing the color of those buttons ('Cancel'/'shutdown').

Then, I customized the show apps button (view-app-grid-button) but when I push the button I see white dots in my customized show apps button. Is there a way to avoid it ?

Finally, what are the parts in the .css file who depends of the color of the menus in the system panel (systray part) ?

Thanks for your answers and your help.

Note: I use the 'dash to panel' extension rather than 'dash to dock'.

News: Show-apps button problem is solved and I found all the parts for the colors of menus in the .css file (popup-menu). But I don't find the solution for the first question.

**Comment by etiennegnome** [comment]
Hi Tuxman2,

GDM has its proper theme you can find in /usr/share/gnome-shell folder.
You can modify it if you know how to decompile the theme and recompile it after your modifications.
I hope I answered your problem.
